apiVersion: v1
kind: ConfigMap
metadata:
  name: jira-config
data:
  dbconfig.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <jira-database-config>
      <name>defaultDS</name>
      <delegator-name>default</delegator-name>
      <database-type>mysql</database-type>

      <jdbc-datasource>
        <url>jdbc:mysql://mysql:3306/jiradb?autoReconnect=true&amp;characterEncoding=utf8&amp;useUnicode=true&amp;sessionVariables=default_storage_engine%3DInnoDB</url>
        <driver-class>com.mysql.jdbc.Driver</driver-class>
        <username>jiradb</username>
        <password>jellyfish</password>
        <pool-min-size>20</pool-min-size>
        <pool-max-size>20</pool-max-size>
        <pool-max-wait>30000</pool-max-wait>
        <pool-max-idle>20</pool-max-idle>
        <pool-remove-abandoned>true</pool-remove-abandoned>
        <pool-remove-abandoned-timeout>300</pool-remove-abandoned-timeout>
        <validation-query>select 1</validation-query>
        <validation-query-timeout>3</validation-query-timeout>
        <min-evictable-idle-time-millis>60000</min-evictable-idle-time-millis>
        <time-between-eviction-runs-millis>300000</time-between-eviction-runs-millis>
        <pool-test-on-borrow>false</pool-test-on-borrow>
        <pool-test-while-idle>true</pool-test-while-idle>
      </jdbc-datasource>
    </jira-database-config>
