apiVersion: v1
kind: Service
metadata:
  name: jira
  labels:
    kubernetes.io/cluster-service: "true"
spec:
  type: NodePort
  selector:
    app: jira
  ports:
  - port: 8080
    name: main
    nodePort: 30000
