apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 999
      containers:
      - name: mysql
        image: mysql:5.7
        #--skip-name-resolve
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: i23j4oihdgho9yd35F
        - name: MYSQL_USER
          value: jiradb
        - name: MYSQL_PASSWORD
          value: jellyfish
        - name: MYSQL_DATABASE
          value: jiradb
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: mysql-data-volume
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: config-volume
          mountPath: /etc/mysql/conf.d
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
      volumes:
      - name: config-volume
        configMap:
          name: mysql-config
  volumeClaimTemplates:
  - metadata:
      name: mysql-data-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
